// Copyright 2021 Red Hat, Inc. and/or its affiliates
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

// KogitoBuildListerExpansion allows custom methods to be added to
// KogitoBuildLister.
type KogitoBuildListerExpansion interface{}

// KogitoBuildNamespaceListerExpansion allows custom methods to be added to
// KogitoBuildNamespaceLister.
type KogitoBuildNamespaceListerExpansion interface{}

// KogitoInfraListerExpansion allows custom methods to be added to
// KogitoInfraLister.
type KogitoInfraListerExpansion interface{}

// KogitoInfraNamespaceListerExpansion allows custom methods to be added to
// KogitoInfraNamespaceLister.
type KogitoInfraNamespaceListerExpansion interface{}

// KogitoRuntimeListerExpansion allows custom methods to be added to
// KogitoRuntimeLister.
type KogitoRuntimeListerExpansion interface{}

// KogitoRuntimeNamespaceListerExpansion allows custom methods to be added to
// KogitoRuntimeNamespaceLister.
type KogitoRuntimeNamespaceListerExpansion interface{}

// KogitoSupportingServiceListerExpansion allows custom methods to be added to
// KogitoSupportingServiceLister.
type KogitoSupportingServiceListerExpansion interface{}

// KogitoSupportingServiceNamespaceListerExpansion allows custom methods to be added to
// KogitoSupportingServiceNamespaceLister.
type KogitoSupportingServiceNamespaceListerExpansion interface{}
