// Copyright 2021 Red Hat, Inc. and/or its affiliates
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

import (
	v1beta1 "github.com/kiegroup/kogito-operator/api/v1beta1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// KogitoRuntimeLister helps list KogitoRuntimes.
// All objects returned here must be treated as read-only.
type KogitoRuntimeLister interface {
	// List lists all KogitoRuntimes in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1beta1.KogitoRuntime, err error)
	// KogitoRuntimes returns an object that can list and get KogitoRuntimes.
	KogitoRuntimes(namespace string) KogitoRuntimeNamespaceLister
	KogitoRuntimeListerExpansion
}

// kogitoRuntimeLister implements the KogitoRuntimeLister interface.
type kogitoRuntimeLister struct {
	indexer cache.Indexer
}

// NewKogitoRuntimeLister returns a new KogitoRuntimeLister.
func NewKogitoRuntimeLister(indexer cache.Indexer) KogitoRuntimeLister {
	return &kogitoRuntimeLister{indexer: indexer}
}

// List lists all KogitoRuntimes in the indexer.
func (s *kogitoRuntimeLister) List(selector labels.Selector) (ret []*v1beta1.KogitoRuntime, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1beta1.KogitoRuntime))
	})
	return ret, err
}

// KogitoRuntimes returns an object that can list and get KogitoRuntimes.
func (s *kogitoRuntimeLister) KogitoRuntimes(namespace string) KogitoRuntimeNamespaceLister {
	return kogitoRuntimeNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// KogitoRuntimeNamespaceLister helps list and get KogitoRuntimes.
// All objects returned here must be treated as read-only.
type KogitoRuntimeNamespaceLister interface {
	// List lists all KogitoRuntimes in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1beta1.KogitoRuntime, err error)
	// Get retrieves the KogitoRuntime from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1beta1.KogitoRuntime, error)
	KogitoRuntimeNamespaceListerExpansion
}

// kogitoRuntimeNamespaceLister implements the KogitoRuntimeNamespaceLister
// interface.
type kogitoRuntimeNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all KogitoRuntimes in the indexer for a given namespace.
func (s kogitoRuntimeNamespaceLister) List(selector labels.Selector) (ret []*v1beta1.KogitoRuntime, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1beta1.KogitoRuntime))
	})
	return ret, err
}

// Get retrieves the KogitoRuntime from the indexer for a given namespace and name.
func (s kogitoRuntimeNamespaceLister) Get(name string) (*v1beta1.KogitoRuntime, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1beta1.Resource("kogitoruntime"), name)
	}
	return obj.(*v1beta1.KogitoRuntime), nil
}
