// Copyright 2021 Red Hat, Inc. and/or its affiliates
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1beta1 "github.com/kiegroup/kogito-operator/api/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeKogitoRuntimes implements KogitoRuntimeInterface
type FakeKogitoRuntimes struct {
	Fake *FakeV1beta1
	ns   string
}

var kogitoruntimesResource = schema.GroupVersionResource{Group: "", Version: "v1beta1", Resource: "kogitoruntimes"}

var kogitoruntimesKind = schema.GroupVersionKind{Group: "", Version: "v1beta1", Kind: "KogitoRuntime"}

// Get takes name of the kogitoRuntime, and returns the corresponding kogitoRuntime object, and an error if there is any.
func (c *FakeKogitoRuntimes) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.KogitoRuntime, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(kogitoruntimesResource, c.ns, name), &v1beta1.KogitoRuntime{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.KogitoRuntime), err
}

// List takes label and field selectors, and returns the list of KogitoRuntimes that match those selectors.
func (c *FakeKogitoRuntimes) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.KogitoRuntimeList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(kogitoruntimesResource, kogitoruntimesKind, c.ns, opts), &v1beta1.KogitoRuntimeList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.KogitoRuntimeList{ListMeta: obj.(*v1beta1.KogitoRuntimeList).ListMeta}
	for _, item := range obj.(*v1beta1.KogitoRuntimeList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested kogitoRuntimes.
func (c *FakeKogitoRuntimes) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(kogitoruntimesResource, c.ns, opts))

}

// Create takes the representation of a kogitoRuntime and creates it.  Returns the server's representation of the kogitoRuntime, and an error, if there is any.
func (c *FakeKogitoRuntimes) Create(ctx context.Context, kogitoRuntime *v1beta1.KogitoRuntime, opts v1.CreateOptions) (result *v1beta1.KogitoRuntime, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(kogitoruntimesResource, c.ns, kogitoRuntime), &v1beta1.KogitoRuntime{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.KogitoRuntime), err
}

// Update takes the representation of a kogitoRuntime and updates it. Returns the server's representation of the kogitoRuntime, and an error, if there is any.
func (c *FakeKogitoRuntimes) Update(ctx context.Context, kogitoRuntime *v1beta1.KogitoRuntime, opts v1.UpdateOptions) (result *v1beta1.KogitoRuntime, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(kogitoruntimesResource, c.ns, kogitoRuntime), &v1beta1.KogitoRuntime{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.KogitoRuntime), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeKogitoRuntimes) UpdateStatus(ctx context.Context, kogitoRuntime *v1beta1.KogitoRuntime, opts v1.UpdateOptions) (*v1beta1.KogitoRuntime, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(kogitoruntimesResource, "status", c.ns, kogitoRuntime), &v1beta1.KogitoRuntime{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.KogitoRuntime), err
}

// Delete takes name of the kogitoRuntime and deletes it. Returns an error if one occurs.
func (c *FakeKogitoRuntimes) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(kogitoruntimesResource, c.ns, name), &v1beta1.KogitoRuntime{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeKogitoRuntimes) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(kogitoruntimesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1beta1.KogitoRuntimeList{})
	return err
}

// Patch applies the patch and returns the patched kogitoRuntime.
func (c *FakeKogitoRuntimes) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.KogitoRuntime, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(kogitoruntimesResource, c.ns, name, pt, data, subresources...), &v1beta1.KogitoRuntime{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.KogitoRuntime), err
}
