apiVersion: v1
kind: Pod
metadata:
  labels:
    name: profiling-data-access
  name: kogito-operator-profiling-data-access
  namespace: kogito-operator-system
spec:
  containers:
  - command:
    - sleep
    - infinity
    image: alpine:latest
    name: alpine
    volumeMounts:
    - mountPath: /data
      name: profiling-data
  volumes:
  - name: profiling-data
    persistentVolumeClaim:
      claimName: kogito-operator-profiling-pvc
