// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta1 "github.com/kiegroup/kogito-operator/client/clientset/versioned/typed/app/v1beta1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeAppV1beta1 struct {
	*testing.Fake
}

func (c *FakeAppV1beta1) KogitoBuilds(namespace string) v1beta1.KogitoBuildInterface {
	return &FakeKogitoBuilds{c, namespace}
}

func (c *FakeAppV1beta1) KogitoInfras(namespace string) v1beta1.KogitoInfraInterface {
	return &FakeKogitoInfras{c, namespace}
}

func (c *FakeAppV1beta1) KogitoRuntimes(namespace string) v1beta1.KogitoRuntimeInterface {
	return &FakeKogitoRuntimes{c, namespace}
}

func (c *FakeAppV1beta1) KogitoSupportingServices(namespace string) v1beta1.KogitoSupportingServiceInterface {
	return &FakeKogitoSupportingServices{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeAppV1beta1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
