scorecard:
  # Setting a global scorecard option
  output: json
  plugins:
    - basic:
        cr-manifest:
          - "deploy/crds/app.kiegroup.org_v1beta1_kogitosupportingservice_cr.yaml"
        csv-path: "deploy/olm-catalog/kogito-operator/1.1.0/kogito-operator.v1.1.0.clusterserviceversion.yaml"
    - olm:
        cr-manifest:
          - "deploy/crds/app.kiegroup.org_v1beta1_kogitosupportingservice_cr.yaml"
        csv-path: "deploy/olm-catalog/kogito-operator/1.1.0/kogito-operator.v1.1.0.clusterserviceversion.yaml"
