apiVersion: app.kiegroup.org/v1beta1
kind: KogitoInfra
metadata:
  # default name
  name: kogito-infinispan-infra
spec:
  resource:
    #APIVersion describes the API Version of referred Kubernetes resource
    apiVersion: infinispan.org/v1
    #Kind describes the kind of referred Kubernetes resource
    kind: Infinispan