apiVersion: app.kiegroup.org/v1alpha1
kind: KogitoDataIndex
metadata:
  name: data-index
spec:
  replicas: 1
  image: quay.io/kiegroup/kogito-data-index:0.12
  kafka:
    useKogitoInfra: true
  infinispan:
    useKogitoInfra: true

