
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - app.kiegroup.org
  resources:
  - kogitobuilds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.kiegroup.org
  resources:
  - kogitobuilds/finalizers
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - app.kiegroup.org
  resources:
  - kogitobuilds/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - app.kiegroup.org
  resources:
  - kogitoinfras
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.kiegroup.org
  resources:
  - kogitoinfras/finalizers
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - app.kiegroup.org
  resources:
  - kogitoinfras/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - app.kiegroup.org
  resources:
  - kogitoruntimes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.kiegroup.org
  resources:
  - kogitoruntimes/finalizers
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - app.kiegroup.org
  resources:
  - kogitoruntimes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - app.kiegroup.org
  resources:
  - kogitosupportingservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.kiegroup.org
  resources:
  - kogitosupportingservices/finalizers
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - app.kiegroup.org
  resources:
  - kogitosupportingservices/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apps
  resources:
  - deployments
  - replicasets
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - build.openshift.io
  resources:
  - buildconfigs
  - builds
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  - events
  - pods
  - secrets
  - serviceaccounts
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  - events
  - pods
  - secrets
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - eventing.knative.dev
  resources:
  - brokers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - eventing.knative.dev
  resources:
  - triggers
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - image.openshift.io
  resources:
  - imagestreams
  - imagestreamtags
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - infinispan.org
  resources:
  - infinispans
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - integreatly.org
  resources:
  - grafanadashboards
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - kafka.strimzi.io
  resources:
  - kafkas
  - kafkatopics
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - keycloak.org
  resources:
  - keycloaks
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - mongodbcommunity.mongodb.com
  resources:
  - mongodbcommunity
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - create
  - delete
  - get
  - list
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - sources.knative.dev
  resources:
  - sinkbindings
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
