// Copyright 2021 Red Hat, Inc. and/or its affiliates
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// Code generated by lister-gen. DO NOT EDIT.

package internalversion

import (
	v1beta1 "github.com/kiegroup/kogito-operator/api/v1beta1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// KogitoBuildLister helps list KogitoBuilds.
// All objects returned here must be treated as read-only.
type KogitoBuildLister interface {
	// List lists all KogitoBuilds in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1beta1.KogitoBuild, err error)
	// KogitoBuilds returns an object that can list and get KogitoBuilds.
	KogitoBuilds(namespace string) KogitoBuildNamespaceLister
	KogitoBuildListerExpansion
}

// kogitoBuildLister implements the KogitoBuildLister interface.
type kogitoBuildLister struct {
	indexer cache.Indexer
}

// NewKogitoBuildLister returns a new KogitoBuildLister.
func NewKogitoBuildLister(indexer cache.Indexer) KogitoBuildLister {
	return &kogitoBuildLister{indexer: indexer}
}

// List lists all KogitoBuilds in the indexer.
func (s *kogitoBuildLister) List(selector labels.Selector) (ret []*v1beta1.KogitoBuild, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1beta1.KogitoBuild))
	})
	return ret, err
}

// KogitoBuilds returns an object that can list and get KogitoBuilds.
func (s *kogitoBuildLister) KogitoBuilds(namespace string) KogitoBuildNamespaceLister {
	return kogitoBuildNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// KogitoBuildNamespaceLister helps list and get KogitoBuilds.
// All objects returned here must be treated as read-only.
type KogitoBuildNamespaceLister interface {
	// List lists all KogitoBuilds in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1beta1.KogitoBuild, err error)
	// Get retrieves the KogitoBuild from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1beta1.KogitoBuild, error)
	KogitoBuildNamespaceListerExpansion
}

// kogitoBuildNamespaceLister implements the KogitoBuildNamespaceLister
// interface.
type kogitoBuildNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all KogitoBuilds in the indexer for a given namespace.
func (s kogitoBuildNamespaceLister) List(selector labels.Selector) (ret []*v1beta1.KogitoBuild, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1beta1.KogitoBuild))
	})
	return ret, err
}

// Get retrieves the KogitoBuild from the indexer for a given namespace and name.
func (s kogitoBuildNamespaceLister) Get(name string) (*v1beta1.KogitoBuild, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1beta1.Resource("kogitobuild"), name)
	}
	return obj.(*v1beta1.KogitoBuild), nil
}
