package api

// Artifact contains override information for building the Maven artifact.
// + optional
// +operator-sdk:gen-csv:customresourcedefinitions.specDescriptors=true
// +operator-sdk:gen-csv:customresourcedefinitions.specDescriptors.displayName="Final Artifact"
type Artifact struct {

	//Indicates the unique identifier of the organization or group that created the project.
	// + optional
	GroupID string `json:"groupId,omitempty"`

	//Indicates the unique base name of the primary artifact being generated.
	// + optional
	ArtifactID string `json:"artifactId,omitempty"`

	//Indicates the version of the artifact generated by the project.
	// + optional
	Version string `json:"version,omitempty"`
}
