# TODO: version management
# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
        environment: GO111MODULE=on
    working_directory: /go/src/github.com/kiegroup/kogito-cloud-operator
    steps:
      - checkout
      - run: go mod tidy
      - run: go mod vendor
      - run: go fmt ./...
      - run: go vet ./...
      - run: go test -mod=vendor ./pkg/... ./cmd/... -count=1
  image_build_push:
    working_directory: /go/src/github.com/kiegroup/kogito-cloud-operator
    docker:
      - image: circleci/golang:1.12
        environment: GO111MODULE=on
    steps:
      - checkout
      - setup_remote_docker
      - run: 
          name: Install dep
          command: curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
      - run:
          name: Install operator-sdk to build image
          command: curl -Lo operator-sdk https://github.com/operator-framework/operator-sdk/releases/download/v0.10.0/operator-sdk-v0.10.0-x86_64-linux-gnu && chmod +x operator-sdk && sudo mv operator-sdk /usr/local/bin/
      - run: make code/build/linux
      - run: make image/build/master
      - run: make image/push/master 
workflows:
  version: 2
  build:
    jobs:
      - build
      - image_build_push
