# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13
        environment: GO111MODULE=on
    working_directory: /go/src/github.com/kiegroup/kogito-cloud-operator
    steps:
      - checkout
      - run: go mod tidy
      - run: go fmt ./...
      - run: go vet ./...
      - run: CGO_ENABLED=0 go test ./cmd/... -count=1 -p=1
      - run: CGO_ENABLED=0 go test ./pkg/... -count=1 -p=1
