# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.13
        environment: GO111MODULE=on
    working_directory: /go/src/github.com/kiegroup/kogito-cloud-operator
    steps:
      - checkout
      - run: go mod tidy
      - run: go fmt ./...
      - run: go vet ./...
      - run: CGO_ENABLED=0 go test -coverprofile test-coverage-cmd.out -json > test-report-cmd.out ./cmd/... -count=1 -p=1
      - run: CGO_ENABLED=0 go test -coverprofile test-coverage-pkg.out -json > test-report-pkg.out ./pkg/... -count=1 -p=1
      - run: git clone https://github.com/bats-core/bats-core.git
      - run: cd bats-core && ./install.sh $HOME
      - run: $HOME/bin/bats hack/*.bats
      - sonarcloud/scan

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.1

workflows:
  main:
    jobs:
      - build:
          context: sonar-cloud-kogito-operator