apiVersion: app.kiegroup.org/v1alpha1
kind: KogitoApp
metadata:
  name: example-quarkus
spec:
  build:
    env:
      # this value is just an example, set yours (optional)
      - name: MAVEN_MIRROR_URL
        value: "http://nexus3.nexus.svc.cluster.local:8081/repository/maven-public/"
     # enable persistence
      - name: MAVEN_ARGS_APPEND
        value: "-Ppersistence"
    gitSource:
      contextDir: jbpm-quarkus-example
      uri: 'https://github.com/kiegroup/kogito-examples'
      reference: 0.7.0
    imageVersion: 0.7.0
