apiVersion: app.kiegroup.org/v1alpha1
kind: KogitoApp
metadata:
  name: example-quarkus
spec:
  build:
    envs:
     # enable persistence
      - name: MAVEN_ARGS_APPEND
        value: "-Ppersistence"
    gitSource:
      contextDir: jbpm-quarkus-example
      uri: 'https://github.com/kiegroup/kogito-examples'
      reference: 0.8.0
    imageVersion: 0.8.0
    # set your maven nexus repository
    #mavenMirrorURL: http://nexus3-nexus.apps-crc.testing/repository/maven-public/