apiVersion: rhpam.kiegroup.org/v1
kind: KogitoBuild
metadata:
  name: example-quarkus
spec:
  type: RemoteSource
  gitSource:
    uri: https://github.com/kiegroup/kogito-examples
    contextDir: process-quarkus-example
---
apiVersion: rhpam.kiegroup.org/v1
kind: KogitoRuntime
metadata:
  name: example-quarkus
spec:
  serviceLabels:
    operator: abc-operator
    app: abc-test
