# permissions for end users to view kogitosupportingservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kogitosupportingservice-viewer-role
rules:
- apiGroups:
  - app.kiegroup.org
  resources:
  - kogitosupportingservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - app.kiegroup.org
  resources:
  - kogitosupportingservices/status
  verbs:
  - get
