# permissions for end users to view kogitobuilds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kogitobuild-viewer-role
rules:
- apiGroups:
  - app.kiegroup.org
  resources:
  - kogitobuilds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - app.kiegroup.org
  resources:
  - kogitobuilds/status
  verbs:
  - get
