# permissions for end users to edit kogitosupportingservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kogitosupportingservice-editor-role
rules:
- apiGroups:
  - app.kiegroup.org
  resources:
  - kogitosupportingservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.kiegroup.org
  resources:
  - kogitosupportingservices/status
  verbs:
  - get
