# permissions for end users to view kogitoinfras.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kogitoinfra-viewer-role
rules:
- apiGroups:
  - app.kiegroup.org
  resources:
  - kogitoinfras
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - app.kiegroup.org
  resources:
  - kogitoinfras/status
  verbs:
  - get
