# permissions for end users to edit kogitoruntimes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kogitoruntime-editor-role
rules:
- apiGroups:
  - app.kiegroup.org
  resources:
  - kogitoruntimes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.kiegroup.org
  resources:
  - kogitoruntimes/status
  verbs:
  - get
