# permissions for end users to edit kogitobuilds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kogitobuild-editor-role
rules:
- apiGroups:
  - app.kiegroup.org
  resources:
  - kogitobuilds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.kiegroup.org
  resources:
  - kogitobuilds/status
  verbs:
  - get
