apiVersion: app.kiegroup.org/v1alpha1
kind: KogitoExplainability
metadata:
  name: explainability
spec:
  # environment variables to set in the runtime container. Example: JAVAOPTS: "-Dquarkus.log.level=DEBUG"
  # env: {}
  # number of pods to be deployed
  replicas: 1
  # httpPort: 8080
  # details about the kafka connection
  kafka:
    # let's leave this burden to KogitoInfra CR to deploy a new Kafka instance for us
    useKogitoInfra: false
  # details about the connected infinispan