apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kogitoapps.app.kiegroup.org
spec:
  group: app.kiegroup.org
  names:
    kind: KogitoApp
    listKind: KogitoAppList
    plural: kogitoapps
    singular: kogitoapp
  scope: Namespaced
  version: v1alpha1
  versions:
    - name: v1alpha1
      served: true
      storage: true
  validation:
    openAPIV3Schema:
      required:
        - spec
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        status:
          type: object
        spec:
          type: object
          required:
            - build
          properties:
            name:
              type: string
            runtime:
              type: string
              description: The name of the runtime used, defaults to quarkus
              enum:
                - quarkus
                - springboot
            replicas:
              type: integer
              format: int32
            build:
              type: object
              required:
                - gitSource
              properties:
                incremental:
                  type: boolean
                gitSource:
                  type: object
                  required:
                    - uri
                  properties:
                    uri:
                      type: string
                      description: Git URI for the s2i source
                    reference:
                      type: string
                      description: Branch to use in the git repository
                    contextDir:
                      type: string
                      description: Context/subdirectory where the code is located, relatively to repo root
                webhooks:
                  type: array
                  minItems: 1
                  items:
                    type: object
                    description: WebHook secretes for build configs
                    required:
                      - type
                      - secret
                    properties:
                      type:
                        type: string
                        description: WebHook type, either GitHub or Generic
                        enum:
                          - GitHub
                          - Generic
                      secret:
                        type: string
                        description: Secret value for webhook
                env:
                  type: array
                  items:
                    type: object
                    required:
                      - name
                    oneOf:
                      - required:
                          - value
                      - required:
                          - valueFrom
                    properties:
                      name:
                        type: string
                        description: Name of an environment variable
                      value:
                        type: string
                        description: Value for that environment variable
                      valueFrom:
                        type: object
                        description: Source for the environment variable's value
            env:
              type: array
              items:
                type: object
                required:
                  - name
                oneOf:
                  - required:
                      - value
                  - required:
                      - valueFrom
                properties:
                  name:
                    type: string
                    description: Name of an environment variable
                  value:
                    type: string
                    description: Value for that environment variable
                  valueFrom:
                    type: object
                    description: Source for the environment variable's value
            resources:
              type: object
              properties:
                limits:
                  type: object
                requests:
                  type: object

