apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "rhpam.kiegroup.org/v1",
          "kind": "KogitoBuild",
          "metadata": {
            "name": "ruleunit-quarkus-example"
          },
          "spec": {
            "gitSource": {
              "contextDir": "ruleunit-quarkus-example",
              "uri": "https://github.com/kiegroup/kogito-examples"
            },
            "type": "RemoteSource"
          }
        },
        {
          "apiVersion": "rhpam.kiegroup.org/v1",
          "kind": "KogitoInfra",
          "metadata": {
            "name": "kogitoinfra-sample"
          },
          "spec": {
            "resource": {
              "apiVersion": "kafka.strimzi.io/v1beta2",
              "kind": "Kafka",
              "name": "kogito-kafka"
            }
          }
        },
        {
          "apiVersion": "rhpam.kiegroup.org/v1",
          "kind": "KogitoRuntime",
          "metadata": {
            "name": "ruleunit-quarkus-example"
          },
          "spec": {
            "replicas": 1
          }
        },
        {
          "apiVersion": "rhpam.kiegroup.org/v1",
          "kind": "KogitoSupportingService",
          "metadata": {
            "name": "kogito-jobs-service"
          },
          "spec": {
            "replicas": 1,
            "serviceType": "JobsService"
          }
        }
      ]
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.10.0+git
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
  name: ibm-bamoe-kogito-operator.v8.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: KogitoBuild
      name: kogitobuilds.rhpam.kiegroup.org
      version: v1
    - kind: KogitoInfra
      name: kogitoinfras.rhpam.kiegroup.org
      version: v1
    - kind: KogitoRuntime
      name: kogitoruntimes.rhpam.kiegroup.org
      version: v1
    - kind: KogitoSupportingService
      name: kogitosupportingservices.rhpam.kiegroup.org
      version: v1
  description: Ibm Bamoe Kogito Operator description. TODO.
  displayName: Ibm Bamoe Kogito Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - apps
          resources:
          - deployments
          - replicasets
          verbs:
          - create
          - delete
          - get
          - list
          - update
          - watch
        - apiGroups:
          - apps
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - build.openshift.io
          resources:
          - buildconfigs
          - builds
          verbs:
          - create
          - delete
          - get
          - list
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - configmaps
          - events
          - pods
          - secrets
          - serviceaccounts
          - services
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - configmaps
          - events
          - pods
          - secrets
          - services
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - eventing.knative.dev
          resources:
          - brokers
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - eventing.knative.dev
          resources:
          - triggers
          verbs:
          - create
          - delete
          - get
          - list
          - update
          - watch
        - apiGroups:
          - image.openshift.io
          resources:
          - imagestreams
          - imagestreamtags
          verbs:
          - create
          - delete
          - get
          - list
          - update
          - watch
        - apiGroups:
          - infinispan.org
          resources:
          - infinispans
          verbs:
          - create
          - delete
          - get
          - list
          - watch
        - apiGroups:
          - integreatly.org
          resources:
          - grafanadashboards
          verbs:
          - create
          - delete
          - get
          - list
          - update
          - watch
        - apiGroups:
          - kafka.strimzi.io
          resources:
          - kafkas
          - kafkatopics
          verbs:
          - create
          - delete
          - get
          - list
          - watch
        - apiGroups:
          - keycloak.org
          resources:
          - keycloaks
          verbs:
          - create
          - delete
          - get
          - list
          - watch
        - apiGroups:
          - mongodb.com
          resources:
          - mongodb
          verbs:
          - create
          - delete
          - get
          - list
          - watch
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - create
          - delete
          - get
          - list
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - rolebindings
          - roles
          verbs:
          - create
          - delete
          - get
          - list
          - update
          - watch
        - apiGroups:
          - rhpam.kiegroup.org
          resources:
          - kogitobuilds
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - rhpam.kiegroup.org
          resources:
          - kogitobuilds/finalizers
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - rhpam.kiegroup.org
          resources:
          - kogitobuilds/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - rhpam.kiegroup.org
          resources:
          - kogitoinfras
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - rhpam.kiegroup.org
          resources:
          - kogitoinfras/finalizers
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - rhpam.kiegroup.org
          resources:
          - kogitoinfras/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - rhpam.kiegroup.org
          resources:
          - kogitoruntimes
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - rhpam.kiegroup.org
          resources:
          - kogitoruntimes/finalizers
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - rhpam.kiegroup.org
          resources:
          - kogitoruntimes/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - rhpam.kiegroup.org
          resources:
          - kogitosupportingservices
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - rhpam.kiegroup.org
          resources:
          - kogitosupportingservices/finalizers
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - rhpam.kiegroup.org
          resources:
          - kogitosupportingservices/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - route.openshift.io
          resources:
          - routes
          verbs:
          - create
          - delete
          - get
          - list
          - update
          - watch
        - apiGroups:
          - sources.knative.dev
          resources:
          - sinkbindings
          verbs:
          - create
          - delete
          - get
          - list
          - update
          - watch
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: rhpam-kogito-operator-controller-manager
      deployments:
      - name: rhpam-kogito-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=10
                image: registry.redhat.io/openshift4/ose-kube-rbac-proxy:v4.10.0
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                  protocol: TCP
                resources: {}
              - args:
                - --health-probe-bind-address=:8081
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                command:
                - /usr/local/bin/rhpam-kogito-operator-manager
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: BUILDER_IMAGE
                  value: bamoe-kogito-builder-rhel8
                - name: RUNTIME_IMAGE
                  value: bamoe-kogito-runtime-jvm-rhel8
                - name: IMAGE_REGISTRY
                  value: registry.redhat.io/ibm-bamoe
                - name: GROUP
                  value: RHPAM
                image: registry.stage.redhat.io/ibm-bamoe/bamoe-kogito-rhel8-operator:8.0.0
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 200m
                    memory: 200Mi
                  requests:
                    cpu: 100m
                    memory: 20Mi
                securityContext:
                  allowPrivilegeEscalation: false
              securityContext:
                runAsNonRoot: true
              serviceAccountName: rhpam-kogito-operator-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: rhpam-kogito-operator-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - ibm-bamoe-kogito-operator
  links:
  - name: Ibm Bamoe Kogito Operator
    url: https://ibm-bamoe-kogito-operator.domain
  maintainers:
  - email: your@email.com
    name: Maintainer Name
  maturity: alpha
  provider:
    name: Provider Name
    url: https://your.domain
  version: 8.0.0-1
