kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kogito-cloud-operator
subjects:
  - kind: ServiceAccount
    name: kogito-cloud-operator
roleRef:
  kind: Role
  name: kogito-cloud-operator
  apiGroup: rbac.authorization.k8s.io

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kogito-service-viewer
  annotations:
    org.kie.kogito/managed-by: Kogito Operator
subjects:
  - kind: ServiceAccount
    name: kogito-service-viewer
roleRef:
  kind: Role
  name: kogito-service-viewer
  apiGroup: rbac.authorization.k8s.io
