apiVersion: v1
kind: ServiceAccount
metadata:
  name: kogito-operator
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: kogito-service-viewer
  annotations:
    org.kie.kogito/managed-by: Kogito Operator