#Keycloak operator should be pre-installed in namespace
apiVersion: app.kiegroup.org/v1beta1
kind: KogitoInfra
metadata:
  name: kogito-keycloak
spec:
  resource:
    apiVersion: keycloak.org/v1alpha1
    kind: Keycloak