#Strimzi operator should be pre-installed in namespace
apiVersion: app.kiegroup.org/v1beta1
kind: KogitoInfra
metadata:
  name: kogito-kafka-infra
spec:
  resource:
    apiVersion: kafka.strimzi.io/v1beta1
    kind: Kafka
---
#Infinispan operator should be pre-installed in namespace
apiVersion: app.kiegroup.org/v1beta1
kind: KogitoInfra
metadata:
  name: kogito-infinispan-infra
spec:
  resource:
    apiVersion: infinispan.org/v1
    kind: Infinispan
---
apiVersion: app.kiegroup.org/v1beta1
kind: KogitoBuild
metadata:
  name: kogito-travel-agency
spec:
  type: RemoteSource
  gitSource:
    uri: "https://github.com/kiegroup/kogito-examples/"
    contextDir: extended/kogito-travel-agency/travels
    reference: master
  # set your maven nexus repository
  #mavenMirrorURL: http://nexus3-nexus.apps-crc.testing/repository/maven-public/
---
apiVersion: app.kiegroup.org/v1beta1
kind: KogitoRuntime
metadata:
  name: kogito-travel-agency
spec:
  infra:
    - kogito-kafka-infra
    - kogito-infinispan-infra