## Defines the list of labels to apply to a PR when there is a change in a specified path
# the default label is applied to all the PRs, other labels will filter based on the files changed on the PR.
# follows the same pattern as reviewers.yml.
# please see the example for the file below

labels:
  - paths:
      - cmd/**
    labels:
      - 'cli 💻'
  - paths:
      - pkg/**
    labels:
      - 'operator :cloud:'
  - paths:
      - test/**
    labels:
      - 'bdd-tests 🧪'
  - paths:
      - Jenkinsfile
    labels:
      - 'CI/CD :loop:'
default:
  - 'needs review :mag:'