review:
  - paths:
      - cmd/**
      - pkg/**
    reviewers:
      - ricardozanini
      - spolti
  - paths:
      - test/**
    reviewers:
      - sutaakar
      - radtriste
  - paths:
      - Jenkinsfile
    reviewers:
      - radtriste
      - Kaitou786
default:
  - ricardozanini
  - spolti