# Adds namespace to all resources.
namespace: kogito-operator-system

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
namePrefix: kogito-operator-

resources:
- bases/profiling_data_access_pod.yaml