apiVersion: app.kiegroup.org/v1alpha1
kind: KogitoBuild
metadata:
  name: onboarding
spec:
  type: RemoteSource
  gitSource:
    uri: https://github.com/kiegroup/kogito-examples
    contextDir: onboarding-example/onboarding
---
apiVersion: app.kiegroup.org/v1alpha1
kind: KogitoRuntime
metadata:
  name: onboarding
spec:
  serviceLabels:
    onboarding: process
  envs:
    - name: NAMESPACE
      value: "<namespace_where_this_app_is_deployed>"
---
apiVersion: app.kiegroup.org/v1alpha1
kind: KogitoBuild
metadata:
  name: hr
spec:
  type: RemoteSource
  gitSource:
    uri: https://github.com/kiegroup/kogito-examples
    contextDir: onboarding-example/hr
---
apiVersion: app.kiegroup.org/v1alpha1
kind: KogitoRuntime
metadata:
  name: hr
spec:
  serviceLabels:
    department/first: process
    id: process
    employee-validation/first: process
---
apiVersion: app.kiegroup.org/v1alpha1
kind: KogitoBuild
metadata:
  name: payroll
spec:
  type: RemoteSource
  gitSource:
    uri: https://github.com/kiegroup/kogito-examples
    contextDir: onboarding-example/payroll
---
apiVersion: app.kiegroup.org/v1alpha1
kind: KogitoRuntime
metadata:
  name: payroll
spec:
  serviceLabels:
    taxes/rate: process
    vacations/days: process
    payments/date: process
