---
#Strimzi operator should be pre-installed in namespace
apiVersion: app.kiegroup.org/v1alpha1
kind: KogitoInfra
metadata:
  name: kogito-kafka-infra
spec:
  resource:
    apiVersion: kafka.strimzi.io/v1beta1
    kind: Kafka
---
#Infinispan operator should be pre-installed in namespace
apiVersion: app.kiegroup.org/v1alpha1
kind: KogitoInfra
metadata:
  name: kogito-infinispan-infra
spec:
  resource:
    apiVersion: infinispan.org/v1
    kind: Infinispan
---
apiVersion: app.kiegroup.org/v1alpha1
kind: KogitoBuild
metadata:
  name: example-quarkus
spec:
  type: RemoteSource
  # set your maven nexus repository
  #mavenMirrorURL: http://nexus3-nexus.apps-crc.testing/repository/maven-public/
  gitSource:
    contextDir: process-quarkus-example
    uri: 'https://github.com/kiegroup/kogito-examples'
  env:
    # enable persistence
    - name: MAVEN_ARGS_APPEND
      value: "-Ppersistence,events"
---
apiVersion: app.kiegroup.org/v1alpha1
kind: KogitoRuntime
metadata:
  name: example-quarkus
spec:
  infra:
    - kogito-kafka-infra
    - kogito-infinispan-infra
