apiVersion: app.kiegroup.org/v1alpha1
kind: KogitoApp
metadata:
  name: example-quarkus-flash
spec:
  build: {}
    # run this from your terminal on your project's root: oc start-build example-quarkus-flash-binary --from-dir=target