apiVersion: app.kiegroup.org/v1alpha1
kind: KogitoBuild
metadata:
  name: example-quarkus
---
apiVersion: app.kiegroup.org/v1alpha1
kind: KogitoRuntime
metadata:
  name: example-quarkus-2
# run this from your terminal on your project's root: oc start-build example-quarkus --from-dir=target