apiVersion: app.kiegroup.org/v1alpha1
kind: KogitoBuild
metadata:
  name: example-springboot
spec:
  type: RemoteSource
  runtime: springboot
  gitSource:
    uri: https://github.com/kiegroup/kogito-examples
    contextDir: process-springboot-example
    reference: master
  disableIncremental: false
  envs:
    - name: CI
      value: "true"
---
apiVersion: app.kiegroup.org/v1alpha1
kind: KogitoRuntime
metadata:
  name: example-springboot
spec:
  runtime: springboot
  envs:
    - name: DEBUG
      value: "true"