apiVersion: app.kiegroup.org/v1alpha1
kind: KogitoBuild
metadata:
  name: kogito-travel-agency
spec:
  type: RemoteSource
  gitSource:
    uri: "https://github.com/kiegroup/kogito-examples/"
    contextDir: extended/kogito-travel-agency/travels
    reference: master
  # set your maven nexus repository
  #mavenMirrorURL: http://nexus3-nexus.apps-crc.testing/repository/maven-public/
---
apiVersion: app.kiegroup.org/v1alpha1
kind: KogitoRuntime
metadata:
  name: kogito-travel-agency
spec:
  infinispan:
    useKogitoInfra: true
  kafka:
    UseKogitoInfra: true