apiVersion: app.kiegroup.org/v1alpha1
kind: KogitoBuild
metadata:
  name: kogito-visas
spec:
  type: RemoteSource
  gitSource:
    uri: 'https://github.com/kiegroup/kogito-travel-agency-tutorial/'
    contextDir: 06-kogito-visas
---
apiVersion: app.kiegroup.org/v1alpha1
kind: KogitoRuntime
metadata:
  name: kogito-visas
spec:
  infinispan:
    useKogitoInfra: true
  kafka:
    UseKogitoInfra: true
  envs:
    - name: MP_MESSAGING_INCOMING_VISASAPPROVED_BOOTSTRAP_SERVERS
    - name: MP_MESSAGING_INCOMING_VISASREJECTED_BOOTSTRAP_SERVERS
    - name: MP_MESSAGING_OUTGOING_VISAAPPLICATIONS_BOOTSTRAP_SERVERS
    - name: MP_MESSAGING_OUTGOING_KOGITO_PROCESSINSTANCES_EVENTS_BOOTSTRAP_SERVERS
    - name: MP_MESSAGING_OUTGOING_KOGITO_USERTASKINSTANCES_EVENTS_BOOTSTRAP_SERVERS
