#Strimzi operator should be pre-installed in namespace
# will set this instance to auto provision an infra structure in the namespace
apiVersion: app.kiegroup.org/v1alpha1
kind: KogitoInfra
metadata:
  name: kogito-kafka-infra
spec:
  resource:
    apiVersion: kafka.strimzi.io/v1beta1
    kind: Kafka
---
#Infinispan operator should be pre-installed in namespace
# will set this instance to auto provision an infra structure in the namespace and attach Infinispan credentials to it
apiVersion: app.kiegroup.org/v1alpha1
kind: KogitoInfra
metadata:
  name: kogito-infinispan-infra
spec:
  resource:
    apiVersion: infinispan.org/v1
    kind: Infinispan
---
apiVersion: app.kiegroup.org/v1alpha1
kind: KogitoSupportingService
metadata:
  name: trusty
spec:
  serviceType: TrustyAI
  # environment variables to set in the runtime container. Example: JAVA_OPTIONS: "-Dquarkus.log.level=DEBUG"
  #env:
    # - name: JAVA_OPTIONS
    #    value: "-Dquarkus.log.level=DEBUG"
  # number of pods to be deployed
  replicas: 1
  # Limits and requests for the Data Index pod
  #memoryLimit: ""
  #memoryRequest: ""
  #cpuLimit: ""
  #cpuRequest: ""
  # details about the kogito infra
  infra:
    - kogito-kafka-infra
    - kogito-infinispan-infra

