apiVersion: operators.coreos.com/v1
kind: OperatorSource
metadata:
  name: kogito-operator
  namespace: openshift-marketplace
spec:
  type: appregistry
  endpoint: https://quay.io/cnr
  registryNamespace: kiegroup
  displayName: "Kogito Operator"
  publisher: "Red Hat"
