# This patch setup the entrypoint-profile for operator profiling
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
spec:
  template:
    spec:
      containers:
      - name: manager
        volumeMounts:
        - mountPath: /tmp/profile
          name: profiling-data
      volumes:
      - name: profiling-data
        persistentVolumeClaim:
          claimName: kogito-operator-profiling-pvc # hardcoded due to claimName not being updated by kustomize cli
