# Strimzi operator should be pre-installed in namespace
# And have installed a Kafka cluster named "kogito-kafka" in the same namespace of the Kogito resources
# Follow these instructions to setup the Kafka cluster:
# https://strimzi.io/docs/operators/latest/quickstart.html
apiVersion: app.kiegroup.org/v1beta1
kind: KogitoInfra
metadata:
  name: kogito-kafka-infra
spec:
  resource:
    apiVersion: kafka.strimzi.io/v1beta2
    kind: Kafka
    name: kogito-kafka
---
apiVersion: app.kiegroup.org/v1beta1
kind: KogitoSupportingService
metadata:
  name: explainability
spec:
  serviceType: Explainability
  # environment variables to set in the runtime container. Example: JAVA_OPTIONS: "-Dquarkus.log.level=DEBUG"
  #env:
    # - name: JAVA_OPTIONS
    #    value: "-Dquarkus.log.level=DEBUG"
  # number of pods to be deployed
  replicas: 1
  # Limits and requests for the Explainability pod
  #memoryLimit: ""
  #memoryRequest: ""
  #cpuLimit: ""
  #cpuRequest: ""
  # details about the kogito infra
  infra:
    - kogito-kafka-infra