apiVersion: app.kiegroup.org/v1beta1
kind: KogitoBuild
metadata:
  name: example-quarkus
spec:
  type: RemoteSource
  gitSource:
    uri: https://github.com/apache/incubator-kie-kogito-examples
    contextDir: process-quarkus-example
---
apiVersion: app.kiegroup.org/v1beta1
kind: KogitoRuntime
metadata:
  name: example-quarkus
spec:
  serviceLabels:
    operator: abc-operator
    app: abc-test
