// Copyright 2021 Red Hat, Inc. and/or its affiliates
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// Code generated by informer-gen. DO NOT EDIT.

package v1beta1

import (
	"context"
	time "time"

	apiv1beta1 "github.com/kiegroup/kogito-operator/api/v1beta1"
	versioned "github.com/kiegroup/kogito-operator/client/clientset/versioned"
	internalinterfaces "github.com/kiegroup/kogito-operator/client/informers/externalversions/internalinterfaces"
	v1beta1 "github.com/kiegroup/kogito-operator/client/listers/core/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// KogitoRuntimeInformer provides access to a shared informer and lister for
// KogitoRuntimes.
type KogitoRuntimeInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1beta1.KogitoRuntimeLister
}

type kogitoRuntimeInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewKogitoRuntimeInformer constructs a new informer for KogitoRuntime type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewKogitoRuntimeInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredKogitoRuntimeInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredKogitoRuntimeInformer constructs a new informer for KogitoRuntime type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredKogitoRuntimeInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AppV1beta1().KogitoRuntimes(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AppV1beta1().KogitoRuntimes(namespace).Watch(context.TODO(), options)
			},
		},
		&apiv1beta1.KogitoRuntime{},
		resyncPeriod,
		indexers,
	)
}

func (f *kogitoRuntimeInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredKogitoRuntimeInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *kogitoRuntimeInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apiv1beta1.KogitoRuntime{}, f.defaultInformer)
}

func (f *kogitoRuntimeInformer) Lister() v1beta1.KogitoRuntimeLister {
	return v1beta1.NewKogitoRuntimeLister(f.Informer().GetIndexer())
}
